################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5/platform/emlib/src/em_cmu.c \
D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5/platform/emlib/src/em_core.c \
D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5/platform/emlib/src/em_emu.c \
D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5/platform/emlib/src/em_gpio.c \
D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5/platform/emlib/src/em_ldma.c \
D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5/platform/emlib/src/em_msc.c \
D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5/platform/emlib/src/em_system.c \
D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5/platform/emlib/src/em_timer.c \
D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5/platform/emlib/src/em_usart.c 

OBJS += \
./simplicity_sdk_2024.6.2/platform/emlib/src/em_cmu.o \
./simplicity_sdk_2024.6.2/platform/emlib/src/em_core.o \
./simplicity_sdk_2024.6.2/platform/emlib/src/em_emu.o \
./simplicity_sdk_2024.6.2/platform/emlib/src/em_gpio.o \
./simplicity_sdk_2024.6.2/platform/emlib/src/em_ldma.o \
./simplicity_sdk_2024.6.2/platform/emlib/src/em_msc.o \
./simplicity_sdk_2024.6.2/platform/emlib/src/em_system.o \
./simplicity_sdk_2024.6.2/platform/emlib/src/em_timer.o \
./simplicity_sdk_2024.6.2/platform/emlib/src/em_usart.o 

C_DEPS += \
./simplicity_sdk_2024.6.2/platform/emlib/src/em_cmu.d \
./simplicity_sdk_2024.6.2/platform/emlib/src/em_core.d \
./simplicity_sdk_2024.6.2/platform/emlib/src/em_emu.d \
./simplicity_sdk_2024.6.2/platform/emlib/src/em_gpio.d \
./simplicity_sdk_2024.6.2/platform/emlib/src/em_ldma.d \
./simplicity_sdk_2024.6.2/platform/emlib/src/em_msc.d \
./simplicity_sdk_2024.6.2/platform/emlib/src/em_system.d \
./simplicity_sdk_2024.6.2/platform/emlib/src/em_timer.d \
./simplicity_sdk_2024.6.2/platform/emlib/src/em_usart.d 


# Each subdirectory must supply rules for building sources it contributes
simplicity_sdk_2024.6.2/platform/emlib/src/em_cmu.o: D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5/platform/emlib/src/em_cmu.c simplicity_sdk_2024.6.2/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c18 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCMSIS_NVIC_VIRTUAL=1' '-DCMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"' '-DSL_CODE_COMPONENT_CORE=core' -I"C:\Users\toan\SimplicityStudio\v5_workspace\bai11111\config" -I"C:\Users\toan\SimplicityStudio\v5_workspace\bai11111\autogen" -I"C:\Users\toan\SimplicityStudio\v5_workspace\bai11111" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/Device/SiliconLabs/EFR32MG21/Include" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/board/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/src" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/CMSIS/Core/Include" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/driver/configuration_over_swo/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/driver/debug/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_init/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/emlib/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc/arm" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/memory_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/toolchain/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/system/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"simplicity_sdk_2024.6.2/platform/emlib/src/em_cmu.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

simplicity_sdk_2024.6.2/platform/emlib/src/em_core.o: D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5/platform/emlib/src/em_core.c simplicity_sdk_2024.6.2/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c18 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCMSIS_NVIC_VIRTUAL=1' '-DCMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"' '-DSL_CODE_COMPONENT_CORE=core' -I"C:\Users\toan\SimplicityStudio\v5_workspace\bai11111\config" -I"C:\Users\toan\SimplicityStudio\v5_workspace\bai11111\autogen" -I"C:\Users\toan\SimplicityStudio\v5_workspace\bai11111" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/Device/SiliconLabs/EFR32MG21/Include" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/board/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/src" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/CMSIS/Core/Include" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/driver/configuration_over_swo/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/driver/debug/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_init/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/emlib/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc/arm" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/memory_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/toolchain/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/system/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"simplicity_sdk_2024.6.2/platform/emlib/src/em_core.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

simplicity_sdk_2024.6.2/platform/emlib/src/em_emu.o: D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5/platform/emlib/src/em_emu.c simplicity_sdk_2024.6.2/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c18 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCMSIS_NVIC_VIRTUAL=1' '-DCMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"' '-DSL_CODE_COMPONENT_CORE=core' -I"C:\Users\toan\SimplicityStudio\v5_workspace\bai11111\config" -I"C:\Users\toan\SimplicityStudio\v5_workspace\bai11111\autogen" -I"C:\Users\toan\SimplicityStudio\v5_workspace\bai11111" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/Device/SiliconLabs/EFR32MG21/Include" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/board/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/src" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/CMSIS/Core/Include" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/driver/configuration_over_swo/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/driver/debug/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_init/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/emlib/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc/arm" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/memory_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/toolchain/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/system/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"simplicity_sdk_2024.6.2/platform/emlib/src/em_emu.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

simplicity_sdk_2024.6.2/platform/emlib/src/em_gpio.o: D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5/platform/emlib/src/em_gpio.c simplicity_sdk_2024.6.2/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c18 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCMSIS_NVIC_VIRTUAL=1' '-DCMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"' '-DSL_CODE_COMPONENT_CORE=core' -I"C:\Users\toan\SimplicityStudio\v5_workspace\bai11111\config" -I"C:\Users\toan\SimplicityStudio\v5_workspace\bai11111\autogen" -I"C:\Users\toan\SimplicityStudio\v5_workspace\bai11111" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/Device/SiliconLabs/EFR32MG21/Include" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/board/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/src" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/CMSIS/Core/Include" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/driver/configuration_over_swo/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/driver/debug/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_init/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/emlib/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc/arm" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/memory_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/toolchain/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/system/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"simplicity_sdk_2024.6.2/platform/emlib/src/em_gpio.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

simplicity_sdk_2024.6.2/platform/emlib/src/em_ldma.o: D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5/platform/emlib/src/em_ldma.c simplicity_sdk_2024.6.2/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c18 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCMSIS_NVIC_VIRTUAL=1' '-DCMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"' '-DSL_CODE_COMPONENT_CORE=core' -I"C:\Users\toan\SimplicityStudio\v5_workspace\bai11111\config" -I"C:\Users\toan\SimplicityStudio\v5_workspace\bai11111\autogen" -I"C:\Users\toan\SimplicityStudio\v5_workspace\bai11111" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/Device/SiliconLabs/EFR32MG21/Include" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/board/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/src" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/CMSIS/Core/Include" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/driver/configuration_over_swo/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/driver/debug/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_init/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/emlib/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc/arm" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/memory_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/toolchain/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/system/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"simplicity_sdk_2024.6.2/platform/emlib/src/em_ldma.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

simplicity_sdk_2024.6.2/platform/emlib/src/em_msc.o: D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5/platform/emlib/src/em_msc.c simplicity_sdk_2024.6.2/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c18 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCMSIS_NVIC_VIRTUAL=1' '-DCMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"' '-DSL_CODE_COMPONENT_CORE=core' -I"C:\Users\toan\SimplicityStudio\v5_workspace\bai11111\config" -I"C:\Users\toan\SimplicityStudio\v5_workspace\bai11111\autogen" -I"C:\Users\toan\SimplicityStudio\v5_workspace\bai11111" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/Device/SiliconLabs/EFR32MG21/Include" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/board/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/src" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/CMSIS/Core/Include" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/driver/configuration_over_swo/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/driver/debug/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_init/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/emlib/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc/arm" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/memory_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/toolchain/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/system/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"simplicity_sdk_2024.6.2/platform/emlib/src/em_msc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

simplicity_sdk_2024.6.2/platform/emlib/src/em_system.o: D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5/platform/emlib/src/em_system.c simplicity_sdk_2024.6.2/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c18 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCMSIS_NVIC_VIRTUAL=1' '-DCMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"' '-DSL_CODE_COMPONENT_CORE=core' -I"C:\Users\toan\SimplicityStudio\v5_workspace\bai11111\config" -I"C:\Users\toan\SimplicityStudio\v5_workspace\bai11111\autogen" -I"C:\Users\toan\SimplicityStudio\v5_workspace\bai11111" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/Device/SiliconLabs/EFR32MG21/Include" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/board/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/src" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/CMSIS/Core/Include" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/driver/configuration_over_swo/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/driver/debug/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_init/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/emlib/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc/arm" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/memory_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/toolchain/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/system/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"simplicity_sdk_2024.6.2/platform/emlib/src/em_system.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

simplicity_sdk_2024.6.2/platform/emlib/src/em_timer.o: D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5/platform/emlib/src/em_timer.c simplicity_sdk_2024.6.2/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c18 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCMSIS_NVIC_VIRTUAL=1' '-DCMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"' '-DSL_CODE_COMPONENT_CORE=core' -I"C:\Users\toan\SimplicityStudio\v5_workspace\bai11111\config" -I"C:\Users\toan\SimplicityStudio\v5_workspace\bai11111\autogen" -I"C:\Users\toan\SimplicityStudio\v5_workspace\bai11111" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/Device/SiliconLabs/EFR32MG21/Include" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/board/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/src" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/CMSIS/Core/Include" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/driver/configuration_over_swo/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/driver/debug/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_init/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/emlib/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc/arm" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/memory_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/toolchain/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/system/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"simplicity_sdk_2024.6.2/platform/emlib/src/em_timer.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

simplicity_sdk_2024.6.2/platform/emlib/src/em_usart.o: D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5/platform/emlib/src/em_usart.c simplicity_sdk_2024.6.2/platform/emlib/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c18 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCMSIS_NVIC_VIRTUAL=1' '-DCMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"' '-DSL_CODE_COMPONENT_CORE=core' -I"C:\Users\toan\SimplicityStudio\v5_workspace\bai11111\config" -I"C:\Users\toan\SimplicityStudio\v5_workspace\bai11111\autogen" -I"C:\Users\toan\SimplicityStudio\v5_workspace\bai11111" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/Device/SiliconLabs/EFR32MG21/Include" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/board/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/src" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/CMSIS/Core/Include" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/driver/configuration_over_swo/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/driver/debug/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_init/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/emlib/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc/arm" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/memory_manager/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/toolchain/inc" -I"D:/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/system/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"simplicity_sdk_2024.6.2/platform/emlib/src/em_usart.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


